Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "controller-prod"

  # Networking: bridged adapter with static IP + MAC
config.vm.network "public_network",
  bridge: "Realtek Gaming GbE Family Controller",
  ip: "192.168.0.2",
  mac: "080027893480"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Controller-Prod"
    vb.memory = 4096
    vb.cpus = 2
  end
end